// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBno5OGhZJd7P7fltrCk0fASPbRQIl7sdQ',
    appId: '1:521461827917:web:a8fa7e9ae8d10230a58f04',
    messagingSenderId: '521461827917',
    projectId: 'krok-test-task',
    authDomain: 'krok-test-task.firebaseapp.com',
    storageBucket: 'krok-test-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UGIT9mN50BgKFFYs6EB-TKmcF37mwKU',
    appId: '1:521461827917:android:e77654039d9d1d6ea58f04',
    messagingSenderId: '521461827917',
    projectId: 'krok-test-task',
    storageBucket: 'krok-test-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMaUdvh77LrSdjZMEVRloBYNJFE3xvhQ',
    appId: '1:521461827917:ios:404a67548140619fa58f04',
    messagingSenderId: '521461827917',
    projectId: 'krok-test-task',
    storageBucket: 'krok-test-task.appspot.com',
    iosBundleId: 'com.example.krokTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMaUdvh77LrSdjZMEVRloBYNJFE3xvhQ',
    appId: '1:521461827917:ios:74248ac7ca60be41a58f04',
    messagingSenderId: '521461827917',
    projectId: 'krok-test-task',
    storageBucket: 'krok-test-task.appspot.com',
    iosBundleId: 'com.example.krokTestTask.RunnerTests',
  );
}
